name: manager
description: "UI part of dpmirror"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  nsd:
    path: ./local_packages/nsd/nsd

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: io.github.tsioam.mirror.manager
    iosBundleIdentifier: io.github.tsioam.mirror.manager
