# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'mirror' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mirror
  pod 'GoogleWebRTC'

  target 'mirrorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mirrorUITests' do
    # Pods for testing
  end

end
